"""enable_timezone_support

Revision ID: f47dbce8c99d
Revises: a0556b7ecc3e
Create Date: 2026-02-14 21:24:22.252062
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f47dbce8c99d'
down_revision: Union[str, None] = 'a0556b7ecc3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('user', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
